name: markhor_sdk
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
dependencies:
  web_socket_channel: ^3.0.1
  autocloud_sdk:
    path: ../../autocloud/autocloud_sdk
  opentelemetry: ^0.18.6
